services:
  dev:
    container_name: flask-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000
    restart: unless-stopped

  prod:
    container_name: flask-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5000" # Notice different external port to avoid conflict with dev
    restart: unless-stopped
